/**
 * Copyright (C) 2025 Karlo Mijaljević
 * <p>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package xyz.mijaljevic.backup_manager.database;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represents a file in the backup system.
 * <p>
 * This class is used to store information about files that are part of the
 * backup process.
 * It includes fields for the file's ID, name, hash, path, MIME type, timestamp
 * when it was noted, and the updated timestamp.
 * <p>
 * The class provides getters and setters for each field, as well as overridden
 * methods for {@code toString()}, {@code equals()}, and {@code hashCode()}.
 */
public final class BackupFile {
    /**
     * Unique ID generated by the database using the autoincrement feature.
     */
    private Long id;

    /**
     * File name with extension.
     */
    private String name;

    /**
     * CRC32 hash of the file.
     */
    private String hash;

    /**
     * Full path of file from the root of the backup directory.
     */
    private String path;

    /**
     * MIME type of the file as deduced by Apache Tika.
     */
    private String type;

    /**
     * Timestamp when the file was first noted/detected.
     */
    private LocalDateTime created;

    /**
     * Timestamp when the file was last updated.
     */
    private LocalDateTime updated;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public LocalDateTime getCreated() {
        return created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    public LocalDateTime getUpdated() {
        return updated;
    }

    public void setUpdated(LocalDateTime updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        return "BackupFile{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", hash='" + hash + '\'' +
                ", path='" + path + '\'' +
                ", type='" + type + '\'' +
                ", created='" + created + '\'' +
                ", updated='" + updated + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        BackupFile that = (BackupFile) o;

        return Objects.equals(id, that.id)
                && Objects.equals(name, that.name)
                && Objects.equals(hash, that.hash)
                && Objects.equals(path, that.path)
                && Objects.equals(type, that.type)
                && Objects.equals(created, that.created)
                && Objects.equals(updated, that.updated);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, hash, path, type, created, updated);
    }
}
